## --project-name
version: '3.8'
services:
    filebeat:
        user: root
        container_name: filebeat-01
        command: --strict.perms=false
        volumes:
            - ./filebeat.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        image: 'docker.elastic.co/beats/filebeat:7.17.0' 
