logging.level: debug
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0600
  
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /monitor/log/messages
  parsers:
    - syslog:
        format: rfc3164
        timezone: Australia/Melbourne
        log_errors: true
        add_error_key: true

output.logstash:
  hosts: ["qa-test.keno:5400"]  
